"""empty message

Revision ID: e13b1643e02d
Revises: 69a9fd3117bc
Create Date: 2023-11-03 16:05:45.181337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13b1643e02d'
down_revision = '69a9fd3117bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consoles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('release_yr', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_games_genre_id_genres')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('console_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('console_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['console_id'], ['consoles.id'], name=op.f('fk_console_games_console_id_consoles')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_console_games_game_id_games')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('console_games')
    op.drop_table('games')
    op.drop_table('genres')
    op.drop_table('consoles')
    # ### end Alembic commands ###
